version: '3.4'

services:   
  catalog.database:
    image: mongo

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/catalog.API/Dockerfile

  basket.database:
    image: redis:alpine

networks:
  default:
    name: microservices-net  